---
title: "Publications"
---

## Please note

I changed my legal name in 2022, hence my previous publication record has a different name.


### First author publications

Rago, Alfredo, John H Werren, and John K Colbourne. 2020.  
“Sex Biased Expression and Co-Expression Networks in Development, Using the Hymenopteran Nasonia   Vitripennis.”  
PLoS Genet 16(1): e1008518.  
https://doi.org/10.1371/journal.pgen.1008518

Rago, Alfredo, Kostas Kouvaris, Tobias Uller, and Richard Watson. 2019.  
“How Adaptive Plasticity Evolves When Selected Against.”   
PLOS Computational Biology 15 (3): e1006260.   
https://doi.org/10.1371/journal.pcbi.1006260.  

Rago, Alfredo, and John Kenneth Colbourne. 2018.   
“FESTA: Flexible Exon-Based Splicing and Transcription Annotation.”   
bioRxiv, 300947.   
https://doi.org/10.1101/300947.  

Rago, Alfredo, Donald G. Gilbert, Jeong-Hyeon Choi, Timothy B. Sackton, Xu Wang, Yogeshwar D. Kelkar, John H. Werren, and John K. Colbourne. 2016.   
“OGS2: Genome Re-Annotation of the Jewel Wasp Nasonia Vitripennis.”   
BMC Genomics 17 (1): 5303.   
https://doi.org/10.1186/s12864-016-2886-9.

Rago, Alfredo, Geoffrey M. While, and Tobias Uller. 2012.  
“Introduction Pathway and Climate Trump Ecology and Life History as Predictors of Establishment  Success in Alien Frogs and Toads.”  
Ecology and Evolution 2 (7): 1437–45. https://doi.org/10.1002/ece3.261. 

### Others

Bornholdt, Jette, Christa Broholm, Yun Chen, **Alfredo Rago**, Stine Sloth, Jakob Hendel, Cathrine Melsæther, et al. 2020.  
“Personalized B Cell Response to the Lactobacillus Rhamnosus GG Probiotic in Healthy Human Subjects: A Randomized Trial.”  
Gut Microbes 12 (1): 1854639.  
https://doi.org/10.1080/19490976.2020.1854639.  

Tobias Uller, Reinder Radersma, Nathalie Feiner, and **Alfredo Rago**. 2019. 
“Developmental Plasticity and Evolutionary Explanations.”  
Evolution & Development.  
https://doi.org/10.1111/ede.12314.  

Feiner, Nathalie, **Alfredo Rago**, Geoffrey M. While, and Tobias Uller. 2018.  
“Developmental Plasticity in Reptiles: Insights from Temperature-Dependent Gene Expression in Wall Lizard Embryos.”  
Journal of Experimental Zoology Part A: Ecological and Integrative Physiology 329 (6-7): 351–61. 
https://doi.org/10.1002/jez.2175. 

Nathalie Feiner, Geoffrey M. While, **Alfredo Rago**, and Tobias Uller. 2018.  
“Signatures of Selection in Embryonic Transcriptomes of Lizards Adapting in Parallel to Cool Climate.”  
Evolution 72 (1): 67–81.  
https://doi.org/10.1111/evo.13397.

Jansen, M., A. N. Geerts, **Alfredo Rago**, K. I. Spanier, C. Denis, L. De Meester, and L. Orsini. 2017.  
“Thermal Tolerance in the Keystone Species Daphnia Magna—a Candidate Gene and an Outlier Analysis Approach.”   
Molecular Ecology 26 (8): 2291–2305.   
https://doi.org/10.1111/mec.14040.  

Wang, Xu, David Wheeler, Amanda Avery, **Alfredo Rago**, Jeong-Hyeon Choi, John K. Colbourne, Andrew G Clark, and John H. Werren. 2013.  
“Function and Evolution of DNA Methylation in Nasonia Vitripennis.”   
PLoS Genetics 9 (10): e1003872.   
https://doi.org/10.1371/journal.pgen.1003872.

